km_all:
	python kmeans.py all ed
km_test:
	python kmeans.py test ed
km_all_cs:
	python kmeans.py all cs
km_test_cs:
	python kmeans.py test cs
db_all:
	python dbscan.py all
db_test:
	python dbscan.py test
db_all_cs:
	python dbscan.py all cs
db_test_cs:
	python dbscan.py test cs
